
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#server:
#  port: 8082



spring:
  h2:
    console: enabled
  datasource:
    url: jdbc:h2:mem:mydb

server:
  port: 8087

logging:
  level:
    org:
      springframework=DEBUG: